---
- name: Get CVE data
  register: r_cve_data
  ansible_tmm.aap_cve_report.cve_info:
    ids: "{{ cve_list }}"

- name: Generate report on execution node
  when: cve_table_output_remote_host is not defined
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ lookup('template', 'templates/interactive_report.html.j2') }}"
    dest: "{{ cve_table_output_dest }}"
    mode: "0664"

- name: Generate report on remote host
  when: cve_table_output_remote_host is defined
  delegate_to: "{{ cve_table_output_remote_host | default('localhost') }}"
  become: "{{ cve_table_become_publish }}"
  ansible.builtin.copy:
    content: "{{ lookup('template', 'templates/interactive_report.html.j2') }}"
    dest: "{{ cve_table_output_dest }}"
    mode: "0664"
