---
- name: Parse package results for reporting
  ansible.builtin.set_fact:
    linux_patch_pkg_output_parsed: "{{ pkg_mgr_output.results | zjleblanc.reporting.parse_updates }}"

- name: Generate services diff
  register: r_post_check
  ansible.utils.fact_diff:
    before: "{{ pre_check_services }}"
    after: "{{ services }}"

- name: Save diff for report
  ansible.builtin.set_fact:
    post_check_diff: "{{ r_post_check.diff_text }}"

- name: Generate report on execution node
  when: linux_patch_output_remote_host is not defined
  delegate_to: localhost
  run_once: "{{ linux_patch_run_once }}"
  ansible.builtin.copy:
    content: "{{ lookup('template', 'templates/report.html.j2') }}"
    dest: "{{ linux_patch_output_dest }}"
    mode: "0664"

- name: Generate report on remote host
  when: linux_patch_output_remote_host is defined
  delegate_to: "{{ linux_patch_output_remote_host | default('localhost') }}"
  run_once: "{{ linux_patch_run_once }}"
  ansible.builtin.copy:
    content: "{{ lookup('template', 'templates/report.html.j2') }}"
    dest: "{{ linux_patch_output_dest }}"
    mode: "0664"
