---
cisco_facts_report_title: "Ansible Cisco Facts Report" # report title
cisco_facts_report_desc: "Ansible Cisco networking report" # report description
cisco_facts_report_hosts: "{{ ansible_play_hosts }}" # report hosts (cisco devices with gathered facts)
cisco_facts_timestamp: "{{ lookup('pipe', 'date +\"%Y-%m-%d @ %H:%M:%S\"') }}" # report timestamp
cisco_facts_output_dest: "{{ playbook_dir }}/zjleblanc.cisco_facts.html" # report html file destination
# cisco_facts_output_remote_host: report_server # inventory host to copy report to
cisco_facts_supported_systems:
  - ios
  - nxos
  - iosxr

cisco_facts_cell_border_color: "white" # device table cell border color
cisco_facts_row_even_background_color: "#f8f9fa" # device table row background color (even rows)
cisco_facts_row_odd_background_color: "#eeeeef" # device table row background color (odd rows)
cisco_facts_tab_color: "#d20101" # tab color for switching content views (Layer 1, ..., etc.)
cisco_facts_group_pill_color: "#17a2b8" # group pill color in ansible facts
